openapi: 3.0.1
info:
  title: pCloud GPT API
  description: API pour accéder aux fichiers pCloud
  version: "1.0"
servers:
  - url: https://pcloud-gpt-mcp.vercel.app

paths:
  /api:
    get:
      summary: Lister les fichiers du dossier racine pCloud
      operationId: listFiles
      responses:
        "200":
          description: Liste de fichiers renvoyée
    post:
      summary: Créer un nouveau dossier
      operationId: createFolder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Résultat de la création du dossier
